<?php

/**
 * Escribe un programa que defina una clase Shapecon un constructor que reciba como parámetros el ancho y alto.
 * Define dos subclases; Triangley Rectangleque hereden de Shapey que calculen respectivamente el área de la forma area().
 * En el archivo main define dos objetos, un triángulo y un rectángulo y llama al método area de cada uno.
 */
class Rectangulo extends Figura {

    public function __construct ($base, $altura) {
        Figura::__construct ($base, $altura); // TODO: Change the autogenerated stub
    }

    public function area () {
        echo "Área Rectángulo: " . $this->area = $this->ancho * $this->alto . "<br/>";
        parent::area();
    }
}